Feat/apply clean arch enhance code quality
moyasar/moyasar-android-sdk pull request #22
Opened 2024-07-26 14:33 UTC by mahmoudashrafmohamed

2024-08-03 10:27 UTC, ahoshaiyan approved these changes

2024-08-03 18:29 UTC, Fghurayri requested changes
Well done @mahmoudashrafmohamed 🙏 

In addition to reviewing my comments, please consider the following for our next round of review:

- Can you please add unit & integration tests.
- We would like to perform a real payment to ensure the E2E flow is working as expected. Can you please peform this step? If you need help, we can coordinate this point in Teams.

2024-08-03 18:29 UTC, Fghurayri commented on sdk/src/main/java/com/moyasar/android/sdk/presentation/viewmodel/PaymentSheetViewModel.kt
> +      "https://sdk.moyasar.com"
If I understand correctly, the value here should be the full RETURN_URL (`https://sdk.moyasar.com/payment/return`) . Can you please confirm?

2024-08-19 21:28 UTC, Fghurayri commented
Excellent job! 👏 @mahmoudashrafmohamed 

Let's connect in Teams to perform a real E2E prior merging this PR! 🚀

2024-08-20 13:12 UTC, Fghurayri approved these changes
We've successfully performed a real payment on Staging (moyasar_cc_qn3cJ5EqLMNgrRUP6imCi6S) and everything worked as expected, alhamdillah. Thank you @mahmoudashrafmohamed 

@ahoshaiyan we are good to go with the release!

2024-08-20 13:13 UTC, merged